In [4]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv")

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv", usecols = ["City"])
pop = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos//Cities.csv", usecols = ["Population"])
pop.head()
#cities.tail()

   Population
0       21722
1        5629
2        5679
3       10085
4       23421

In [6]:
cities.head()

            City
0         Kajuru
1           Leon
2            Osh
3  Shumikhinskiy
4       Bundoran

In [7]:
cities.tail()

        City
596  Lobitos
597   Bremen
598   Harare
599    Lagos
600   Oshawa

In [8]:
pop.tail(n = 8)

     Population
593       16755
594       16325
595       16905
596       10024
597        5768
598       16679
599       24800
600       13000

In [9]:
cities.count()

City    601
dtype: int64

In [10]:
pop.count()

Population    601
dtype: int64

In [11]:
cities.describe()

               City
count           601
unique          578
top     San Antonio
freq              4

In [12]:
pop.describe()

         Population
count    601.000000
mean   13932.415973
std     6765.873291
min     2528.000000
25%     7801.000000
50%    13966.000000
75%    19752.000000
max    38745.000000

In [13]:
#cities.sort_values()
cities.sort_values(by = ["City"], ascending = False)

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang
..             ...
467       Alcoutim
212       Alarobia
472          Aketi
66          Aizhai
581          Abuja

[601 rows x 1 columns]

In [14]:
cities.sort_values(by = ["City"], ascending = False).head()

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang

In [15]:
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv", usecols = ["City"])
cities
cities.sort_values(by = ["City"], ascending = False, inplace = True)
cities

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang
..             ...
467       Alcoutim
212       Alarobia
472          Aketi
66          Aizhai
581          Abuja

[601 rows x 1 columns]

In [16]:
cities.sort_index()

              City
0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
..             ...
596        Lobitos
597         Bremen
598         Harare
599          Lagos
600         Oshawa

[601 rows x 1 columns]

In [17]:
#cities
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv")
cities.sort_index(ascending = True, inplace = True)
cities

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [18]:
print(cities)

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [19]:
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv")
data

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [62]:
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos//Cities.csv", index_col = ["City"])
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv", usecols = ["City"])
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv")
data.head()

            City     Country  Population
0         Kajuru    Botswana       21722
1           Leon       Spain        5629
2            Osh  kyrgyzstan        5679
3  Shumikhinskiy      Russia       10085
4       Bundoran     Ireland       23421

In [61]:
data[1]

KeyError: 1

In [22]:
cities = data["City"]
cities.head()

0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
Name: City, dtype: object

In [24]:
cities[600]

'Oshawa'

In [25]:
cities[10:20]

10            Ise
11         Volovo
12         Caujul
13     Kutloanong
14       Kobuleti
15         Senlis
16         Wufeng
17         Picton
18    Johor Bahru
19     Fort Worth
Name: City, dtype: object

In [26]:
cities[:15]

0            Kajuru
1              Leon
2               Osh
3     Shumikhinskiy
4          Bundoran
5         La Paloma
6             Tutup
7           Ondores
8           Heredia
9              Gaio
10              Ise
11           Volovo
12           Caujul
13       Kutloanong
14         Kobuleti
Name: City, dtype: object

In [27]:
cities[:26:2]

0          Kajuru
2             Osh
4        Bundoran
6           Tutup
8         Heredia
10            Ise
12         Caujul
14       Kobuleti
16         Wufeng
18    Johor Bahru
20     Santa Cruz
22         Maubin
24          Itzer
Name: City, dtype: object

In [28]:
cities[-10:]

591    Bagumbayan
592      Tuanshan
593       Sapporo
594    Cocachacra
595        Kurjan
596       Lobitos
597        Bremen
598        Harare
599         Lagos
600        Oshawa
Name: City, dtype: object

In [29]:
cities[[3, 5, 7]]
#cities.sort_values()

3    Shumikhinskiy
5        La Paloma
7          Ondores
Name: City, dtype: object

In [30]:
#Retrieving data from a series by index label:

#city = pd.read_csv("Cities.csv", usecols = ["City", "Country"])
city = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv", usecols = ["City", "Country"], index_col = "City")
city = city["Country"]
city

City
Kajuru             Botswana
Leon                  Spain
Osh              kyrgyzstan
Shumikhinskiy        Russia
Bundoran            Ireland
                    ...
Lobitos                Peru
Bremen              Germany
Harare             Zimbabwe
Lagos               Nigeria
Oshawa               Canada
Name: Country, Length: 601, dtype: object

In [31]:
city[0]

<ipython-input-31-8f5a1a4338dc>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city[0]

'Botswana'

In [32]:
city["Lobitos"]

City
Lobitos    Peru
Lobitos    Peru
Name: Country, dtype: object

In [33]:
city["Kajuru"]

'Botswana'

In [34]:
city.sort_index(inplace = True, ascending = True)
city

City
Abuja                                     Nigeria
Aizhai                                      China
Aketi            Democratic Republic of the Congo
Alarobia                               Madagascar
Alcoutim                                 Portugal
                               ...
Zhongshangang                               China
Zhongshangang                               China
Zhongxing                                   China
Zhuoshui                                    China
Zliv                               Czech Republic
Name: Country, Length: 601, dtype: object

In [35]:
city["Abuja":"Bremen"]

City
Abuja                                 Nigeria
Aizhai                                  China
Aketi        Democratic Republic of the Congo
Alarobia                           Madagascar
Alcoutim                             Portugal
                           ...
Bolgar                                 Russia
Bomomani                            Indonesia
Bonavista                              Canada
Bradag                              Indonesia
Bremen                                Germany
Name: Country, Length: 84, dtype: object

In [36]:
city[:"Bremen"]

City
Abuja                                 Nigeria
Aizhai                                  China
Aketi        Democratic Republic of the Congo
Alarobia                           Madagascar
Alcoutim                             Portugal
                           ...
Bolgar                                 Russia
Bomomani                            Indonesia
Bonavista                              Canada
Bradag                              Indonesia
Bremen                                Germany
Name: Country, Length: 84, dtype: object

In [37]:
city[["Bolgar", "Abuja", "Osh"]]

City
Bolgar        Russia
Abuja        Nigeria
Osh       kyrgyzstan
Name: Country, dtype: object

In [38]:
city.head(10)

City
Abuja                                      Nigeria
Aizhai                                       China
Aketi             Democratic Republic of the Congo
Alarobia                                Madagascar
Alcoutim                                  Portugal
Alis                                          Peru
Alvaro Obregon                              Mexico
Amargosa                                    Brazil
Amuru                                       Uganda
Anan                                         Japan
Name: Country, dtype: object

In [39]:
city["Abuja": "Anan": 2]

City
Abuja                                      Nigeria
Aketi             Democratic Republic of the Congo
Alcoutim                                  Portugal
Alvaro Obregon                              Mexico
Amuru                                       Uganda
Name: Country, dtype: object

In [40]:
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Archivos/Cities.csv", usecols = ["City", "Country"], index_col = "City")
data.sort_index(inplace = True)
data

                                        Country
City
Abuja                                   Nigeria
Aizhai                                    China
Aketi          Democratic Republic of the Congo
Alarobia                             Madagascar
Alcoutim                               Portugal
...                                         ...
Zhongshangang                             China
Zhongshangang                             China
Zhongxing                                 China
Zhuoshui                                  China
Zliv                             Czech Republic

[601 rows x 1 columns]

In [41]:
city = data["Country"]
city

City
Abuja                                     Nigeria
Aizhai                                      China
Aketi            Democratic Republic of the Congo
Alarobia                               Madagascar
Alcoutim                                 Portugal
                               ...
Zhongshangang                               China
Zhongshangang                               China
Zhongxing                                   China
Zhuoshui                                    China
Zliv                               Czech Republic
Name: Country, Length: 601, dtype: object

In [42]:
city.get(0)

<ipython-input-42-3b8953b357aa>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city.get(0)

'Nigeria'

In [43]:
city.get([1, 5])

<ipython-input-43-4615aa7bec12>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city.get([1, 5])

City
Aizhai    China
Alis       Peru
Name: Country, dtype: object

In [44]:
#city.get(["Aizahai", "Alis"])
print(city.get(["Aizahai", "Alis"]))

None

In [45]:
print(city.get(780))

None

<ipython-input-45-bc7c82276ab4>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(city.get(780))

In [46]:
city.dtype      #To veriry that cuty is an object 'o'

dtype('O')

In [47]:
city.values

array(['Nigeria', 'China', 'Democratic Republic of the Congo',
       'Madagascar', 'Portugal', 'Peru', 'Mexico', 'Brazil', 'Uganda',
       'Japan', 'Peru', 'China', 'Ukraine', 'Chile', 'China', 'Canada',
       'Peru', 'United Arab Emirates', 'Argentina', 'Colombia',
       'Portugal', 'Portugal', 'Netherlands', 'France', 'Brazil',
       'Brazil', 'Armenia', 'Armenia', 'France', 'France', 'Paraguay',
       'Philippines', 'Ireland', 'Philippines', 'China', 'China', 'China',
       'Portugal', 'Dominican Republic', 'Philippines',
       'Bosnia and Herzegovina', 'Portugal', 'Thailand', 'Thailand',
       'Thailand', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia',
       'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Eritrea',
       'Philippines', 'Oman', 'France', 'China', 'China', 'Brazil',
       'Peru', 'Indonesia', 'Mexico', 'Ukraine', 'Lebanon', 'Philippines',
       'Philippines', 'China', 'Nepal', 'Indonesia', 'Chad', 'Indonesia',
       'France', 'Thailand', 'Ecuador', 'Venezuela', 'Sweden',
       'Indonesia', 'Poland', 'Russia', 'Indonesia', 'Canada',
       'Indonesia', 'Germany', 'France', 'United Kingdom', 'Mexico',
       'Chile', 'Philippines', 'Philippines', 'New Zealand', 'Pakistan',
       'Indonesia', 'Democratic Republic of the Congo', 'Ireland',
       'Gambia', 'Tanzania', 'Indonesia', 'Philippines', 'Peru', 'China',
       'Egypt', 'Mauritius', 'Peru', 'Brazil', 'Brazil', 'China',
       'Portugal', 'Philippines', 'Philippines', 'Guatemala', 'Ireland',
       'Philippines', 'Philippines', 'Peru', 'Indonesia', 'France',
       'Zambia', 'China', 'China', 'Afghanistan', 'France', 'China',
       'Colombia', 'Mongolia', 'Ukraine', 'Czech Republic', 'China',
       'China', 'China', 'Indonesia', 'Indonesia', 'Indonesia',
       'Indonesia', 'Indonesia', 'Indonesia', 'Portugal', 'Indonesia',
       'Indonesia', 'Dominican Republic', 'China', 'Philippines', 'Peru',
       'Indonesia', 'Bolivia', 'Philippines', 'Philippines', 'Portugal',
       'Brazil', 'Portugal', 'Brazil', 'China', 'South Korea', 'China',
       'China', 'Indonesia', 'Philippines', 'China', 'China', 'Sweden',
       'Canada', 'United States', 'China', 'Nigeria', 'China', 'Russia',
       'Indonesia', 'Netherlands', 'Bonaire, Saint Eustatius and Saba ',
       'Poland', 'Poland', 'Philippines', 'Philippines', 'China',
       'Belarus', 'Nigeria', 'Portugal', 'Argentina', 'Panama',
       'Nicaragua', 'Mexico', 'Panama', 'Dominican Republic',
       'Netherlands', 'Mongolia', 'China', 'China', 'Portugal', 'Germany',
       'Russia', 'Poland', 'Micronesia', 'Indonesia', 'Russia', 'Nigeria',
       'Russia', 'Colombia', 'United States', 'Canada', 'Denmark',
       'Norway', 'France', 'Indonesia', 'Portugal', 'Portugal', 'China',
       'China', 'China', 'China', 'China', 'Indonesia', 'Indonesia',
       'Indonesia', 'Afghanistan', 'Nigeria', 'Indonesia', 'South Korea',
       'Colombia', 'Venezuela', 'Mexico', 'China', 'Japan', 'Indonesia',
       'China', 'China', 'South Korea', 'Estonia', 'China', 'China',
       'Indonesia', 'China', 'Zimbabwe', 'China', 'Indonesia', 'China',
       'China', 'China', 'Colombia', 'Sweden', 'China', 'Costa Rica',
       'China', 'China', 'China', 'China', 'Sri Lanka', 'Japan', 'France',
       'United States', 'Egypt', 'Madagascar', 'Nigeria', 'Japan',
       'United States', 'Russia', 'United States', 'Japan', 'Iran',
       'Russia', 'Mexico', 'Brazil', 'Morocco', 'Brazil', 'Sweden',
       'Malaysia', 'Philippines', 'Armenia', 'Indonesia', 'Kenya',
       'Botswana', 'Russia', 'Slovenia', 'Botswana', 'Japan',
       'Philippines', 'Uganda', 'Indonesia', 'Croatia', 'Indonesia',
       'Indonesia', 'Yemen', 'Thailand', 'Tajikistan', 'Thailand',
       'Finland', 'Philippines', 'Sudan', 'Russia', 'Croatia',
       'Indonesia', 'Indonesia', 'Georgia', 'Japan', 'Estonia',
       'Bulgaria', 'Indonesia', 'Malaysia', 'Malaysia', 'Malaysia',
       'Ukraine', 'Russia', 'Sweden', 'Albania', 'Thailand', 'Thailand',
       'South Africa', 'Zimbabwe', 'Czech Republic', 'Kyrgyzstan', 'Peru',
       'Mexico', 'Vietnam', 'Mexico', 'Uruguay', 'Brazil', 'Nigeria',
       'Philippines', 'Brazil', 'Portugal', 'Portugal', 'Sweden',
       'France', 'Armenia', 'Indonesia', 'Philippines', 'Brazil',
       'Thailand', 'France', 'South Africa', 'Spain', 'France', 'Myanmar',
       'Indonesia', 'Indonesia', 'South Africa', 'Russia', 'Russia',
       'Indonesia', 'Comoros', 'Russia', 'France', 'Ukraine', 'Swaziland',
       'Peru', 'Peru', 'Portugal', 'Philippines', 'Uruguay', 'Peru',
       'Russia', 'Zambia', 'Ecuador', 'Spain', 'Philippines',
       'Philippines', 'Madagascar', 'Philippines', 'Philippines',
       'Colombia', 'Russia', 'New Zealand', 'Philippines', 'Pakistan',
       'Brazil', 'Indonesia', 'Indonesia', 'Indonesia', 'Brazil',
       'Russia', 'Indonesia', 'Pakistan', 'Yemen', 'Peru', 'Myanmar',
       'Russia', 'Taiwan', 'United States', 'Botswana', 'Myanmar',
       'Chile', 'Mali', 'Canada', 'Japan', 'Pakistan', 'France', 'France',
       'United States', 'Myanmar', 'Ukraine', 'Indonesia', 'Ukraine',
       'Ukraine', 'Malawi', 'Indonesia', 'Thailand', 'Thailand', 'Sweden',
       'Canada', 'Colombia', 'South Korea', 'Portugal', 'Portugal',
       'Peru', 'Indonesia', 'Poland', 'Maldives', 'United States',
       'Belarus', 'Belarus', 'Indonesia', 'kyrgyzstan', 'Canada',
       'Canada', 'Philippines', 'Thailand', 'Colombia', 'Indonesia',
       'Philippines', 'Indonesia', 'Indonesia', 'Indonesia', 'Chile',
       'Indonesia', 'Indonesia', 'France', 'Indonesia', 'Armenia',
       'Indonesia', 'United States', 'Portugal', 'Russia', 'New Zealand',
       'Peru', 'Thailand', 'South Africa', 'Zimbabwe', 'Philippines',
       'Cape Verde', 'Cape Verde', 'Slovenia', 'Canada', 'Russia',
       'Poland', 'Russia', 'Peru', 'Russia', 'Russia', 'Portugal',
       'Portugal', 'France', 'France', 'Brazil', 'Indonesia', 'Portugal',
       'Brazil', 'United States', 'Philippines', 'Indonesia',
       'Netherlands', 'France', 'Philippines', 'Czech Republic',
       'Netherlands', 'Russia', 'Dominican Republic', 'Syria',
       'Philippines', 'Philippines', 'Senegal', 'Canada',
       'Palestinian Territory', 'Malawi', 'Thailand', 'Indonesia',
       'Indonesia', 'Finland', 'Thailand', 'Mexico', 'United States',
       'United States', 'Chile', 'Argentina', 'Guatemala', 'Philippines',
       'Mexico', 'Mexico', 'Philippines', 'Philippines', 'Panama',
       'Brazil', 'Brazil', 'Japan', 'Russia', 'Indonesia', 'Indonesia',
       'Brazil', 'Sierra Leone', 'Portugal', 'Macedonia', 'Indonesia',
       'Indonesia', 'Indonesia', 'France', 'Russia', 'Philippines',
       'Czech Republic', 'United States', 'Georgia', 'Russia', 'Thailand',
       'Canada', 'Morocco', 'Russia', 'Comoros', 'Indonesia', 'Indonesia',
       'Russia', 'South Korea', 'Peru', 'Russia', 'Russia', 'Portugal',
       'Russia', 'Serbia', 'Bulgaria', 'Russia', 'Sweden', 'Bulgaria',
       'Poland', 'Bolivia', 'South Korea', 'Indonesia', 'Indonesia',
       'Indonesia', 'Nigeria', 'Indonesia', 'Sweden', 'Russia', 'Japan',
       'Indonesia', 'Czech Republic', 'Indonesia', 'Portugal', 'China',
       'Philippines', 'Philippines', 'China', 'Philippines', 'Ethiopia',
       'China', 'Guinea', 'Spain', 'Russia', 'Canada', 'Honduras',
       'Thailand', 'Norway', 'China', 'Philippines', 'Philippines',
       'China', 'Indonesia', 'Indonesia', 'Czech Republic', 'Philippines',
       'Indonesia', 'Indonesia', 'Sweden', 'Russia', 'Russia',
       'Palestinian Territory', 'Ukraine', 'Finland', 'Tajikistan',
       'Papua New Guinea', 'Argentina', 'Russia', 'Albania', 'China',
       'New Zealand', 'Canada', 'Kenya', 'China', 'China', 'Indonesia',
       'China', 'China', 'Nigeria', 'Poland', 'Ukraine', 'Netherlands',
       'China', 'China', 'Russia', 'China', 'Russia', 'China', 'China',
       'China', 'China', 'Czech Republic'], dtype=object)

In [48]:
population = pop
population

     Population
0         21722
1          5629
2          5679
3         10085
4         23421
..          ...
596       10024
597        5768
598       16679
599       24800
600       13000

[601 rows x 1 columns]

In [49]:
population = pop["Population"]
population

0      21722
1       5629
2       5679
3      10085
4      23421
       ...
596    10024
597     5768
598    16679
599    24800
600    13000
Name: Population, Length: 601, dtype: int64

In [50]:
population.dtype

dtype('int64')

In [51]:
#pop.values
population.values

array([21722,  5629,  5679, 10085, 23421, 22154, 11558, 13288,  5835,
        9942, 18354,  8184,  4672, 10733, 16577, 13265, 38745, 10120,
       16567, 24397, 15170,  5589, 17693,  2545, 21997, 11174, 21758,
        5860, 13204, 24943,  7476, 18560, 16422, 20559,  8519, 24805,
       20119,  5283, 19947, 16254,  9746,  4187,  3515, 22829,  4431,
       11071,  5972, 23638,  5217, 19156, 24196,  3106,  5428, 20167,
       15519, 24424, 20539, 13138, 11393, 22345, 19021, 22267, 23801,
       19485,  2653,  8634, 10173,  2528,  7332, 18425, 16527,  3103,
       22667,  6901,  5532, 24272, 20178, 14050, 22908, 22016, 10667,
       12517, 21987,  3900, 16041,  3507,  4002, 13997, 21675, 13299,
       11913, 24383, 14784, 14841,  2863, 16916, 13234,  5349, 22436,
       12620, 10021, 20120, 20168, 21621,  3695, 24722, 18096, 15913,
       19734, 17535, 13034,  4291, 18899, 21153, 12967, 17231, 23458,
       15394, 17005,  4779,  9960, 14226, 13161, 13443,  6955,  8307,
        7193, 13518, 14385, 10188,  5470, 17720, 21409, 11147, 13966,
       13041, 21697,  3200,  3005, 12141, 18956,  2972, 19063,  4962,
       12426, 14596, 11859, 18173,  5611,  3571, 15853,  6255, 13471,
       19698, 11250, 19580, 23588, 24437,  3241,  7960, 23179,  9431,
       12626, 24666, 21762,  3587,  4718, 20044, 23203,  6128, 15691,
        4930,  9031, 20048, 14258, 18716,  4181,  8103,  2568, 11008,
       16102,  3590, 12138,  7305, 24995, 15642, 22334, 21408,  3517,
        6013, 22762,  8531, 15223, 19066, 13500, 11236, 15189, 15509,
        6348, 13232, 13272, 14500, 21095, 12316, 12321,  7891, 20061,
        8776,  5482, 17317,  7830, 18615, 17492,  7641, 11549, 17235,
       18605,  4143, 10196, 24325, 20967, 17620,  4157, 18941, 13596,
       13161,  3867,  3912,  2581, 19090,  7251, 18192, 12353, 20756,
       20208,  8650, 14298, 24248, 17394, 22346,  6419, 17373, 23184,
       15229, 12186,  2533, 24789,  7337, 20537, 18399, 12021, 24391,
       22589, 13603,  5386, 22900, 16650,  8247, 12718,  6348, 24060,
       16111,  3467, 18244, 23793, 22181, 22168, 11901, 15224, 16306,
       21340, 20551, 17272,  7331,  2752, 24020, 11693,  3295,  2936,
       15775, 13827, 10896,  9929, 20654, 15348,  4681,  3045, 23061,
       18726, 20079, 21465,  9850, 23005, 14668,  5661,  7446, 15090,
       10277,  9122, 23690, 12433, 18118,  4352, 21721, 22601,  8055,
       19890,  7252,  3826, 21146, 11618,  4517, 10444, 21774, 12835,
        3162, 12282, 24771,  3960, 23053, 16040,  4231,  2574, 20111,
       22001, 21790,  7689,  9936, 17818, 16783, 22054, 20220, 21183,
       15897,  4534, 21600, 24095,  4539, 12736,  5851,  3020, 16395,
       23665, 22968, 12765, 22175,  6504,  7969, 24670, 16996, 18126,
       12242, 12348,  3885,  5415, 12126, 20512, 15738, 21540,  2862,
       12397, 24614, 19686, 13014, 10688, 12411, 16375, 18678, 16148,
       13872, 16996,  4654, 23396, 19101,  4978,  3622, 17663, 18705,
        5763, 23452, 15496, 18741,  8022, 18205, 20144,  5247,  3416,
       10496,  9367, 24722, 15864, 11267,  3610, 20361, 18007, 14073,
       24475,  6833, 21271, 21938,  4065, 19752, 23290, 20067, 16208,
       21270, 16389,  9808, 13423, 22811, 18435,  9430,  5247, 13627,
       18243,  7127, 22095,  3370, 17647, 18066,  2797, 12076,  3596,
       21216,  2772, 17560, 11364, 13086, 22781,  4984, 15368, 11291,
       13344, 21760, 24385, 22361, 23914,  8612, 10223, 15487, 22073,
        9632,  4812, 12541, 24958,  2809,  6699, 14768, 16258, 11630,
       24800, 14918, 11090,  7801, 11761,  4201,  6376,  6507, 19797,
       14989, 13989,  8550, 13430, 21824, 16421, 12001, 24186, 22000,
       11553, 11688, 18159, 11645, 21555,  6655, 15734, 18856,  4617,
        8882, 12530, 14436,  7791,  3163,  3946, 10175, 24808,  5379,
        6520,  7049, 22750, 11695, 13252,  3284, 18819, 11151, 19895,
       11064,  9725,  5230,  6165,  4455, 16381, 19337, 20739,  5841,
        6281, 15649,  3126, 13875,  3358,  4949, 12666, 10440, 14053,
       24989,  9593, 16078, 16386,  7322, 13885,  7347, 24753, 17549,
       19366, 17631,  6961,  8209, 23796,  7299, 23804,  6942, 13500,
       16973, 16832, 19525, 24090, 24669, 15031, 21275,  6105, 19443,
       14669, 18373, 20383, 23981,  3135, 13448, 12112,  5356,  5964,
       15892,  5273, 15770, 15923,  9106, 13275, 16795, 22569, 14495,
       22342, 13766,  7307, 21426, 10701, 16307, 10710, 12357, 19005,
       22671,  7514, 13979,  4602,  6759, 19212, 10634,  6658,  5048,
       19561, 21988, 21421,  8361, 10012, 17400, 21444, 24751, 18087,
        6055, 18843, 21704, 11094,  3803, 23737, 11949,  4114, 16755,
       16325, 16905, 10024,  5768, 16679, 24800, 13000])

In [52]:
city.index

Index(['Abuja', 'Aizhai', 'Aketi', 'Alarobia', 'Alcoutim', 'Alis',
       'Alvaro Obregon', 'Amargosa', 'Amuru', 'Anan',
       ...
       'Zhangcun', 'Zhangzhu', 'Zhatay', 'Zhentou', 'Zhiletovo',
       'Zhongshangang', 'Zhongshangang', 'Zhongxing', 'Zhuoshui', 'Zliv'],
      dtype='object', name='City', length=601)

In [53]:
population.index

RangeIndex(start=0, stop=601, step=1)

In [54]:
city.is_unique

False

In [55]:
population.is_unique

False

In [56]:
city.ndim

1

In [57]:
#pop.ndim
population.ndim

1