In [6]:
import pandas as pd

In [7]:
data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]}

In [8]:
pd.DataFrame(data)

    name  age  gender
0  Sally    4  female
1   Jhon    6    male
2    Kim    7    male

In [9]:
pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"])

       name  age  gender
Kid1  Sally    4  female
Kid2   Jhon    6    male
Kid3    Kim    7    male